application: sample
version: 1
runtime: go
api_version: go1

handlers:

- url: /(.*\.html)
  static_files: html/\1
  upload: html/.*\.html

- url: /(js/.*\.js)
  static_files: \1
  upload: js/.*\.js

- url: /(.*.css)
  static_files: \1
  upload: .*\.css

- url: /.*
  script: _go_app
